In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

PROJECT_DIR = '~/github/reddit-sentiment-analysis'

In [9]:
df_posts = pd.read_parquet(f'{PROJECT_DIR}/data/posts.parquet.brotli', engine='pyarrow')
df_posts = df_posts[['subreddit', 'title']]
df_posts.head()

   subreddit                                              title
0  AskReddit       What Worst possible reply to "I'm pregnant"?
1  AskReddit  What is a personal story you have that you don...
2  AskReddit     How did that person in your class become rich?
3  AskReddit      What is the worst reply to “I’m leaving you”?
4  AskReddit    Who's the Most Dangerous Human Alive Right Now?

# References
- https://www.kaggle.com/code/sudalairajkumar/getting-started-with-text-preprocessing#Lemmatization
- https://www.kaggle.com/code/abdmental01/text-preprocessing-nlp-steps-to-process-text#Text-Preprocessing-in-NLP-%7C-Basis-Steps-to-Preprocess-The-Textual-Data-

# 1. Lower Casing

In [13]:
df_posts['title'] = df_posts['title'].str.lower()
df_posts.head()

   subreddit                                              title
0  AskReddit       what worst possible reply to "i'm pregnant"?
1  AskReddit  what is a personal story you have that you don...
2  AskReddit     how did that person in your class become rich?
3  AskReddit      what is the worst reply to “i’m leaving you”?
4  AskReddit    who's the most dangerous human alive right now?